### ISSUE TITLE
Also check that authority is set for new modules, if other modules in the dist do exist

### ISSUE THREAD

**Issue by karenetheridge** [charsbar/Test-PAUSE-Permissions#3]
When a new module is being uploaded (for the first time), if the authority data is not set, the uploader will get first-come on the new module -- so the authority user won't be able to do another release.  This is a problem if there are other modules already in the index for the distribution - they will have mismatched permissions.

**Comment by karenetheridge** [comment]
Oops, I found a link to this issue buried in a TODO file!  Sorry about that.

Here's an example:

* GAAS has first-come over the HTTP-Message distribution and the modules in it (HTTP::Message, HTTP::Headers, etc).
* I have comaint on these modules as well.
* I'm going to make a new release (call it version 6.15), but I'm also adding a new module to the distribution, let's call it HTTP::Headers::Encoded.
* since I am the first uploader for this module, I'll get first-come for it in the permissions database. (Now this distribution has inconsistent permissions.)
* now GAAS wants to make a release (version 6.16). HTTP::Message and HTTP::Headers are indexed, but he doesn't have permissions on HTTP::Headers::Encoded!  That module will display as "UNAUTHORIZED" on metacpan, and people cannot install the latest distribution from `cpanm HTTP::Headers::Encoded" (they'll get the older HTTP-Message-6.15 that I made).

**Comment by karenetheridge** [comment]
Also, since the time of creating this issue, I have written: https://metacpan.org/release/Dist-Zilla-Plugin-AuthorityFromModule

..which sketches out an idea to prevent these issues from occurring.  PAUSE hasn't yet adopted this metadata though.

**Comment by karenetheridge** [comment]
..and I see I also included a sample scenario here -- https://metacpan.org/pod/Dist::Zilla::Plugin::AuthorityFromModule#MOTIVATION

**Comment by charsbar** [comment]
Thanks for the explanation. Noted in my todo list for the coming QAH.

**Comment by charsbar** [comment]
@karenetheridge, could you review the above commit when you have some time to see if it satisfies your need?

**Comment by karenetheridge** [comment]
This looks correct! many thanks!

**Comment by charsbar** [comment]
Thanks! Shipped 0.06.
