### ISSUE TITLE
idea: use MetaCPAN module permission index

### ISSUE THREAD

**Issue by skaji** [charsbar/Test-PAUSE-Permissions#5]
Now MetaCPAN has a module permission index.
We could check module permissions via MetaCPAN faster than fetching whole 06perms.txt.
I think it would be nice that Test-PAUSE-Permissions uses MetaCPAN.

The following is a example of querying module permissions to MetaCPAN. 
```
# request
curl https://fastapi.metacpan.org/v1/permission/_search -d '
{
   "query" : {
      "bool" : {
         "should" : [
            { "term" : { "module_name" : "JSON::PP" } },
            { "term" : { "module_name" : "JSON::PP::Boolean" } },
            { "term" : { "module_name" : "JSON::PP::IncrParser" } }
         ]
      }
   },
   "size" : 3
}
'

# response
{
   "_shards" : {
      "total" : 3,
      "successful" : 3,
      "failed" : 0
   },
   "took" : 3,
   "timed_out" : false,
   "hits" : {
      "hits" : [
         {
            "_source" : {
               "module_name" : "JSON::PP",
               "co_maintainers" : [
                  "ISHIGAKI"
               ],
               "owner" : "MAKAMAKA"
            },
            "_type" : "permission",
            "_score" : 3.0540767,
            "_index" : "cpan_v1_01",
            "_id" : "JSON::PP"
         },
         {
            "_source" : {
               "co_maintainers" : [
                  "ISHIGAKI"
               ],
               "owner" : "MAKAMAKA",
               "module_name" : "JSON::PP::Boolean"
            },
            "_type" : "permission",
            "_score" : 3.0540767,
            "_index" : "cpan_v1_01",
            "_id" : "JSON::PP::Boolean"
         },
         {
            "_source" : {
               "owner" : "MAKAMAKA",
               "co_maintainers" : [
                  "ISHIGAKI"
               ],
               "module_name" : "JSON::PP::IncrParser"
            },
            "_type" : "permission",
            "_score" : 2.98695,
            "_id" : "JSON::PP::IncrParser",
            "_index" : "cpan_v1_01"
         }
      ],
      "total" : 3,
      "max_score" : 3.0540767
   }
}
```
cf https://github.com/skaji/App-CPANPermission/blob/master/lib/App/CPANPermission.pm#L47-L65

**Comment by charsbar** [comment]
IMO it's more appropriate to ask PAUSE::Permissions to add an option to support MetaCPAN. Note that PAUSE::Permissions should keep the current load-everything-in-memory behavior as well because we may use it to test lots of distributions (eg. the whole CPAN).

When it's done, I'll happily add an option to Test::PAUSE::Permissions :)

**Comment by skaji** [comment]
Sure.

**Comment by skaji** [comment]
@charsbar If I create PAUSE::Permissions::MetaCPAN, do you accept a patch to use it?

Background:
Minilla creates xt/minilla/permissions.t which uses Test-PAUSE-Permissions.
It may take quite a long time if  our internet connection is slow.
So I want to make Test::PAUSE::Permissions fast.

**Comment by charsbar** [comment]
@skaji Now you have a collaborator/comaintainer bit for GitHub and PAUSE :)

As this is for release testing, I don't think we need to check internet connection, but if you think it helps (for testing, backcompat etc), please add the check as well.

Also, if MetaCPAN returns permissions of multiple packages, it might be better to query less (with more parameters). I haven't tested it myself, but as long as the public interface is intact, I'd welcome any change. Beware distributions with *a lot of* packages, like Paws (https://metacpan.org/release/Paws) for example, though, for performance, and for politeness to MetaCPAN. You might want to consult MetaCPAN people before you release a new version.

Anyway, thanks and ping me if you want me to review/help or whatever.

**Comment by skaji** [comment]
@charsbar Thanks!

> Beware distributions with a lot of packages, like Paws (https://metacpan.org/release/Paws) for example, though, for performance, and for politeness to MetaCPAN.

We can get permissions of multiple packages at once from MetaCPAN.
In fact, the example in my first comment gets permissions of JSON::PP, JSON::PP::Boolean and JSON::PP::IncrParser at once.

I will work on this.
